'use strict'
// default settings for lab test runs.
//
// This is overridden if arguments are passed to lab via the command line.
module.exports = {
  verbose: true,
  coverage: true,
  // Means when we use *.only() in our tests we just get the output for what we've flagged rather than all output but
  // greyed out to show it was skipped
  'silent-skips': true,
  // lcov reporter required for SonarCloud
  reporter: ['console', 'html', 'lcov'],
  output: ['stdout', 'coverage/coverage.html', 'coverage/lcov.info'],
  globals: [
    '__classPrivateFieldGet',
    '__classPrivateFieldIn',
    '__extends',
    '__assign',
    '__rest',
    '__decorate',
    '__param',
    '__metadata',
    '__awaiter',
    '__generator',
    '__exportStar',
    '__values',
    '__read',
    '__spread',
    '__spreadArrays',
    '__await',
    '__asyncGenerator',
    '__asyncDelegator',
    '__asyncValues',
    '__makeTemplateObject',
    '__importStar',
    '__importDefault',
    '__classPrivateFieldSet',
    'version',
    'payload',
    'fetch',
    'Response',
    'Headers',
    'Request',
    '__coverage__',
    '__createBinding',
    '__spreadArray',
    'AggregateError',
    'atob',
    'btoa',
    'AbortController',
    'AbortSignal',
    'EventTarget',
    'Event',
    'MessageChannel',
    'MessagePort',
    'MessageEvent',
    'performance',
    'BroadcastChannel',
    'structuredClone',
    'DOMException',
    'Blob',
    'Performance',
    'ReadableStream',
    'ReadableStreamDefaultReader',
    'ReadableStreamBYOBReader',
    'ReadableStreamBYOBRequest',
    'ReadableByteStreamController',
    'ReadableStreamDefaultController',
    'TransformStream',
    'TransformStreamDefaultController',
    'WritableStream',
    'WritableStreamDefaultWriter',
    'WritableStreamDefaultController',
    'ByteLengthQueuingStrategy',
    'CountQueuingStrategy',
    'TextEncoderStream',
    'TextDecoderStream',
    'CompressionStream',
    'DecompressionStream',
    'FormData',
    'Symbol(undici.globalDispatcher.1)'
  ].join(',')
};
