'use strict'

/**
 * Void any return logs which do not match those determined by the import job
 * @module
 */

const db = require('../../../lib/connectors/db.js')
const { voidReturnLogs } = require('../lib/queries.js')

/**
 * Void any return logs which do not match those determined by the import job
 *
 * @param  {string} licenceRef - The licence reference of the licence being processed
 * @param  {object[]} rows - rows of return logs generated by the import
 */
async function go (licenceRef, rows) {
  const returnIds = rows.map((row) => {
    return row.return_id
  })

  await db.query(voidReturnLogs, [licenceRef, returnIds])
}

module.exports = {
  go
}
