'use strict'

/**
 * Void any return logs which do not match those determined by the import job
 * @module
 */

const db = require('../../../lib/connectors/db.js')

const QUERY = `
UPDATE "returns"."returns"
SET
  status = 'void',
  updated_at = now()
WHERE
  regime = 'water'
  AND licence_type = 'abstraction'
  AND licence_ref = $1
  AND NOT (return_id = ANY ($2));
`

/**
 * Void any return logs which do not match those determined by the import job
 *
 * @param  {string} licenceRef - The licence reference of the licence being processed
 * @param  {object[]} rows - rows of return logs generated by the import
 */
async function go (licenceRef, rows) {
  const returnIds = rows.map((row) => {
    return row.return_id
  })

  await db.query(QUERY, [licenceRef, returnIds])
}

module.exports = {
  go
}
